"""Guarded offline policy search and human-attributed promotion."""

from __future__ import annotations

import json
from copy import deepcopy
from datetime import UTC, datetime
from typing import Any

from .contracts import validate_id, validate_policy
from .evaluator import evaluate_policy
from .store import LabStore, StoreError


def _candidate_policies(base: dict[str, Any]) -> list[dict[str, Any]]:
    floor_options = (
        {"low": 0.30, "medium": 0.45, "high": 0.65, "critical": 0.80},
        {"low": 0.40, "medium": 0.55, "high": 0.72, "critical": 0.86},
    )
    candidates: list[dict[str, Any]] = []
    for quality in (0.45, 0.60, 0.75):
        for cost in (0.10, 0.20, 0.30):
            latency = round(1.0 - quality - cost, 10)
            if latency < 0.05:
                continue
            for abstain_below in (0.30, 0.45, 0.60):
                for floors in floor_options:
                    candidate = {
                        "id": "optimizer-search-candidate",
                        "description": "Ephemeral score policy generated by bounded grid search.",
                        "method": "score",
                        "eligible_kinds": deepcopy(base["eligible_kinds"]),
                        "fallback_target": base["fallback_target"],
                        "normalization": deepcopy(base["normalization"]),
                        "weights": {
                            "quality": quality,
                            "cost": cost,
                            "latency": latency,
                        },
                        "abstain_below": abstain_below,
                        "quality_floor_by_risk": deepcopy(floors),
                    }
                    validate_policy(candidate)
                    candidates.append(candidate)
    return candidates


def _is_guardrail_safe(
    candidate: dict[str, Any],
    baseline: dict[str, Any],
    objective: dict[str, Any],
) -> bool:
    candidate_metrics = candidate["metrics"]
    baseline_metrics = baseline["metrics"]
    guardrails = objective["hard_guardrails"]
    return (
        candidate_metrics["hard_violation_rate"] <= guardrails["max_hard_violation_rate"]
        and candidate_metrics["task_success_rate"]
        >= baseline_metrics["task_success_rate"] - guardrails["max_success_regression"]
    )


def optimize_policy(
    store: LabStore,
    base_policy: dict[str, Any],
    *,
    objective: dict[str, Any] | None = None,
    suite: str = "development",
    persist: bool = True,
    actor: str = "optimizer",
) -> dict[str, Any]:
    """Search development partitions and emit a proposal; never auto-activate."""

    chosen_objective = objective or store.active_objective()
    if suite == "confirmation":
        raise StoreError("optimizer is forbidden from using the confirmation suite")
    cases = store.list("case", suite=suite)
    partitions = {case["partition"] for case in cases}
    if "confirmation" in partitions:
        raise StoreError("optimizer input contains confirmation-partition cases")
    if not {"train", "validation"}.issubset(partitions):
        raise StoreError("optimizer requires both train and validation partitions")

    base_train = evaluate_policy(
        store,
        base_policy,
        objective=chosen_objective,
        suite=suite,
        partitions={"train"},
    )
    base_validation = evaluate_policy(
        store,
        base_policy,
        objective=chosen_objective,
        suite=suite,
        partitions={"validation"},
    )
    ranked: list[dict[str, Any]] = []
    for candidate in _candidate_policies(base_policy):
        train = evaluate_policy(
            store,
            candidate,
            objective=chosen_objective,
            suite=suite,
            partitions={"train"},
        )
        validation = evaluate_policy(
            store,
            candidate,
            objective=chosen_objective,
            suite=suite,
            partitions={"validation"},
        )
        ranked.append(
            {
                "policy": candidate,
                "train": train,
                "validation": validation,
                "safe": _is_guardrail_safe(validation, base_validation, chosen_objective),
            }
        )

    safe = [entry for entry in ranked if entry["safe"]]
    if not safe:
        raise StoreError("no candidate matched the validation guardrails")
    winner = max(
        safe,
        key=lambda entry: (
            entry["validation"]["metrics"]["objective_score"],
            entry["train"]["metrics"]["objective_score"],
            -entry["validation"]["metrics"]["total_cost_usd"],
        ),
    )
    improvement = (
        winner["validation"]["metrics"]["objective_score"]
        - base_validation["metrics"]["objective_score"]
    )
    winner_policy = deepcopy(winner["policy"])
    fingerprint_source = {
        "base": store.resource_hash(base_policy),
        "dataset": store.dataset_hash(suite),
        "objective": store.resource_hash(chosen_objective),
        "policy": winner_policy,
    }
    fingerprint = store.resource_hash(fingerprint_source)
    winner_policy["id"] = f"candidate-{fingerprint[:12]}"
    winner_policy["description"] = (
        f"Optimizer proposal derived from {base_policy['id']} on {suite}; "
        "not approved for live or scientific use."
    )
    validate_policy(winner_policy)

    proposal_id = f"proposal-{fingerprint[:16]}"
    proposal = {
        "schema_version": "1.0",
        "id": proposal_id,
        "status": "pending_human_approval",
        "generated_at": datetime.now(UTC).isoformat(),
        "mode": "simulation_only",
        "suite": suite,
        "dataset_sha256": store.dataset_hash(suite),
        "base_policy_id": base_policy["id"],
        "base_policy_sha256": store.resource_hash(base_policy),
        "objective_id": chosen_objective["id"],
        "objective_sha256": store.resource_hash(chosen_objective),
        "candidate_policy": winner_policy,
        "search": {
            "algorithm": "bounded_grid_search",
            "candidate_count": len(ranked),
            "selection_partition": "validation",
            "confirmation_accessed": False,
        },
        "baseline": {
            "train": base_train["metrics"],
            "validation": base_validation["metrics"],
        },
        "candidate": {
            "train": winner["train"]["metrics"],
            "validation": winner["validation"]["metrics"],
        },
        "validation_objective_improvement": improvement,
        "promotion_allowed": (
            improvement >= float(chosen_objective["meaningful_improvement"])
            and winner["safe"]
        ),
        "required_next_step": (
            "Human reviews raw case results and may apply only to the local simulation state. "
            "A separate governed gate is required for confirmation, scientific, online, or production use."
        ),
    }
    if persist:
        store.initialize_runtime()
        path = store.runtime / "proposals" / f"{proposal_id}.json"
        path.write_text(json.dumps(proposal, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        proposal["artifact_path"] = str(path)
        store.audit(
            actor=actor,
            action="optimization.proposed",
            details={
                "proposal_id": proposal_id,
                "base_policy_id": base_policy["id"],
                "candidate_policy_id": winner_policy["id"],
                "promotion_allowed": proposal["promotion_allowed"],
            },
        )
    return proposal


def list_proposals(store: LabStore) -> list[dict[str, Any]]:
    store.initialize_runtime()
    proposals: list[dict[str, Any]] = []
    for path in sorted((store.runtime / "proposals").glob("*.json")):
        proposal = json.loads(path.read_text(encoding="utf-8"))
        proposals.append(
            {
                "id": proposal["id"],
                "status": proposal["status"],
                "base_policy_id": proposal["base_policy_id"],
                "candidate_policy_id": proposal["candidate_policy"]["id"],
                "objective_id": proposal["objective_id"],
                "path": str(path),
            }
        )
    return proposals


def read_proposal(store: LabStore, proposal_id: str) -> dict[str, Any]:
    safe_id = validate_id(proposal_id, "proposal_id")
    path = store.runtime / "proposals" / f"{safe_id}.json"
    if not path.is_file():
        raise StoreError(f"proposal {proposal_id!r} does not exist")
    proposal = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(proposal, dict):
        raise StoreError(f"proposal {proposal_id!r} is not an object")
    return proposal


def apply_proposal(store: LabStore, proposal_id: str, *, approved_by: str) -> dict[str, Any]:
    if not approved_by.strip() or approved_by.strip().lower() in {"agent", "unknown", "auto"}:
        raise StoreError("approved_by must identify a human reviewer")
    proposal = read_proposal(store, proposal_id)
    if proposal["status"] != "pending_human_approval":
        raise StoreError(f"proposal status is {proposal['status']!r}, not pending_human_approval")
    if not proposal.get("promotion_allowed"):
        raise StoreError("proposal did not clear development promotion criteria")
    if store.dataset_hash(proposal["suite"]) != proposal["dataset_sha256"]:
        raise StoreError("proposal is stale because the development dataset changed")
    base = store.get("policy", proposal["base_policy_id"])
    if store.resource_hash(base) != proposal["base_policy_sha256"]:
        raise StoreError("proposal is stale because the base policy changed")
    objective = store.get("objective", proposal["objective_id"])
    if store.resource_hash(objective) != proposal["objective_sha256"]:
        raise StoreError("proposal is stale because the evaluation objective changed")
    candidate = proposal["candidate_policy"]
    validate_policy(candidate)
    store.put("policy", candidate, actor=approved_by)
    state = store.state()
    state["active_policy"] = candidate["id"]
    state["active_objective"] = objective["id"]
    state["last_approved_by"] = approved_by
    state["last_proposal_id"] = proposal_id
    store.write_state(state, actor=approved_by)
    proposal["status"] = "applied_to_simulation"
    proposal["approved_by"] = approved_by
    proposal["applied_at"] = datetime.now(UTC).isoformat()
    path = store.runtime / "proposals" / f"{proposal_id}.json"
    path.write_text(json.dumps(proposal, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    store.audit(
        actor=approved_by,
        action="proposal.applied",
        details={"proposal_id": proposal_id, "policy_id": candidate["id"]},
    )
    return proposal


def delete_proposal(store: LabStore, proposal_id: str, *, actor: str) -> dict[str, Any]:
    proposal = read_proposal(store, proposal_id)
    path = store.runtime / "proposals" / f"{proposal_id}.json"
    path.unlink()
    store.audit(
        actor=actor,
        action="proposal.delete",
        details={"proposal_id": proposal_id, "previous_status": proposal.get("status")},
    )
    return {"deleted": proposal_id, "previous_status": proposal.get("status")}
